
# Tarea 1
### Maestría en ciencia de datos
### Estephania Pivac Alcaraz

## 1. Descargando los datos

Comenzamos cargando las bibliotecas necesarias.

In [1]:
import os  # Para manejo de archivos y directorios
import urllib.request # Una forma estandard de descargar datos
# import requests # Otra forma no de las librerías de uso comun

import datetime # Fecha de descarga
import pandas as pd # Solo para ver el archivo descargado
import zipfile # Descompresión de archivos

Creamos los subdirectorios para guardar los datos de manera ordenada.

In [9]:
# pwd
print(os.getcwd())

#  Estos son los datos que vamos a descargar y donde vamos a guardarlos
mortalidad_2020_url = "https://www.inegi.org.mx/contenidos/programas/mortalidad/datosabiertos/defunciones/2020/conjunto_de_datos_defunciones_registradas_2020_csv.zip"
mortalidad_2020_archivo = "mortalidad_2020"

salud_particulares_2020_url = "https://www.inegi.org.mx/contenidos/programas/salud/datosabiertos/conjunto_de_datos_esep_2020_csv.zip"
salud_particulares_2020_archivo = "salud_2020.zip"
subdir = "./data/"

/content

Revisamos si ya existen los subdirectorios. Si no es así los creamos. 

Enseguida, abrimos las url de los archivos, extraemos contenidos de los zip y los guardamos.

In [10]:
# Revisamos si el archivo existe. Si no existe, se procede a crearlo.
if not os.path.exists(mortalidad_2020_archivo):
    # Revisamos si el directorio existe. Si no es así procedemos a crearlo.
    if not os.path.exists(subdir):
        #Creamos el directorio 
        os.makedirs(subdir)
    # Abrimos la url y guardamos el objeto en mortalidad_2020_archivo
    urllib.request.urlretrieve(mortalidad_2020_url, subdir + mortalidad_2020_archivo)  
    # Extraemos el contenido del zip y lo guardamos.
    with zipfile.ZipFile(subdir + mortalidad_2020_archivo, "r") as zip_ref:
        zip_ref.extractall(subdir)

if not os.path.exists(salud_particulares_2020_archivo):
    urllib.request.urlretrieve(salud_particulares_2020_url, subdir + salud_particulares_2020_archivo) 
    with zipfile.ZipFile(subdir + salud_particulares_2020_archivo, "r") as zip_ref:
        zip_ref.extractall(subdir)

Creamos un archivo tipo txt, con la información de las bases de datos y las fuentes de donde obtuvimos la información.

In [11]:
with open(subdir + "info.txt", 'w') as f:
  f.write("Archivos sobre mortalidad \n")
  info = """
  mortalidad_2020: La estadística de defunciones registra la información sobre el 
  fenómeno de la mortalidad en el país,que permite conocer y comparar el volumen, 
  tendencia y características de la mortalidad en los diferentes ámbitos geográficos
  del país, conformando un insumo para el análisis y evaluación de acciones dirigidas 
  a la elaboración de programas de salud pública.

  En esta base de datos Se captan las defunciones registradas en todo el país en el 
  Sistema de Registro Civil, así como las defunciones accidentales y violentas en 
  las que intervienen el Servicio Médico Forense y el Ministerio Público.

  salud_2020: Estas estadísticas abordan los datos sobre servicios, morbilidad 
  hospitalaria, así como recursos humanos y materiales proporcionados por las 
  instituciones privadas.


  Los datos se obtuvieron de datos abiertos del INEGI con fechas de 27 de agosto 2022.

  """ 
  f.write(info + '\n')
  f.write("Descargado el " + datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S") + "\n")
  f.write("Desde: " + mortalidad_2020_url + "\n")
  f.write("Nombre: " + mortalidad_2020_archivo + "\n")
  f.write("Agregados salud en establecimientos particulades descargados desde: " + salud_particulares_2020_url + "\n")
  f.write("Nombre: " + salud_particulares_2020_archivo + "\n")

**¿Qué variables vienen en los conjuntos de datos que descargaste (en forma muy genética)? ¿Par qué te interesan estos datos? Para entender tus intereses.**

Dado que las bases de datos sobre mastografías contenían muy poca información (pocas variables), he decididio cambiar las bases de datos. 

Encontré una base de datos muy interesante, que es sobre la mortalidad, y me interesa estudiar las principales causas, de acuerdo al sexo, edad, datos geográficos, etc.

\

**¿Podrás realizar los comandos para obtener el dataframe tal como dices y probar si sirve o no? Me parece que te vas a llevar una sorpresa y el descargar y acomodar los datos que te interesan va a ser un poco más complicado de lo que parece a simple vista. Tu decide cual es la información que te interesa, y cuales serían los archivos que tendrías que abrir. (hay muchos).**

A continuación aparecen los data frames de las bases de datos. Me parece que podría seleccionar algunas variables específicas, ya que la base de datos es muy extensa.

### Mortalidad

Exploremos la primera base de datos

In [19]:
df_mortalidad = pd.read_csv("/content/data/conjunto_de_datos/conjunto_de_datos_defunciones_registradas_2020.csv")

df_mortalidad.head()

,ent_regis,mun_regis,ent_resid,mun_resid,tloc_resid,loc_resid,ent_ocurr,mun_ocurr,tloc_ocurr,loc_ocurr,...,anio_cert,maternas,lengua,cond_act,par_agre,ent_ocules,mun_ocules,loc_ocules,razon_m,dis_re_oax
0,1,1,1,1,15,1,1,1,15,1,...,2020,NaN,2,9,88,88,888,8888,0,999
1,1,1,1,1,15,1,1,1,15,1,...,2020,NaN,9,9,88,88,888,8888,0,999
2,1,1,1,1,15,1,1,1,15,1,...,2020,NaN,2,2,88,88,888,8888,0,999
3,1,1,1,1,15,1,1,1,15,1,...,2020,NaN,9,9,88,88,888,8888,0,999
4,1,6,1,9,4,1,1,9,4,1,...,2020,NaN,2,1,88,88,888,8888,0,999

In [21]:
df_mortalidad.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1086743 entries, 0 to 1086742
Data columns (total 59 columns):
 #   Column      Non-Null Count    Dtype
---  ------      --------------    -----
 0   ent_regis   1086743 non-null  int64
 1   mun_regis   1086743 non-null  int64
 2   ent_resid   1086743 non-null  int64
 3   mun_resid   1086743 non-null  int64
 4   tloc_resid  1086743 non-null  int64
 5   loc_resid   1086743 non-null  int64
 6   ent_ocurr   1086743 non-null  int64
 7   mun_ocurr   1086743 non-null  int64
 8   tloc_ocurr  1086743 non-null  int64
 9   loc_ocurr   1086743 non-null  int64
 10  causa_def   1086743 non-null  object
 11  lista_mex   1086743 non-null  object
 12  sexo        1086743 non-null  int64
 13  edad        1086743 non-null  int64
 14  dia_ocurr   1086743 non-null  int64
 15  mes_ocurr   1086743 non-null  int64
 16  anio_ocur   1086743 non-null  int64
 17  dia_regis   1086743 non-null  int64
 18  mes_regis   1086743 non-null  int64
 19  anio_regis  1086743 non-null  int64
 20  dia_nacim   1086743 non-null  int64
 21  mes_nacim   1086743 non-null  int64
 22  anio_nacim  1086743 non-null  int64
 23  ocupacion   1086743 non-null  int64
 24  escolarida  1086743 non-null  int64
 25  edo_civil   1086743 non-null  int64
 26  presunto    1086743 non-null  int64
 27  ocurr_trab  1086743 non-null  int64
 28  lugar_ocur  1086743 non-null  int64
 29  necropsia   1086743 non-null  int64
 30  asist_medi  1086743 non-null  int64
 31  sitio_ocur  1086743 non-null  int64
 32  cond_cert   1086743 non-null  int64
 33  nacionalid  1086743 non-null  int64
 34  derechohab  1086743 non-null  int64
 35  embarazo    1086743 non-null  int64
 36  rel_emba    1086743 non-null  int64
 37  horas       1086743 non-null  int64
 38  minutos     1086743 non-null  int64
 39  capitulo    1086743 non-null  int64
 40  grupo       1086743 non-null  int64
 41  lista1      1086743 non-null  int64
 42  gr_lismex   1086743 non-null  object
 43  vio_fami    1086743 non-null  int64
 44  area_ur     1086743 non-null  int64
 45  edad_agru   1086743 non-null  int64
 46  complicaro  1086743 non-null  int64
 47  dia_cert    1086743 non-null  int64
 48  mes_cert    1086743 non-null  int64
 49  anio_cert   1086743 non-null  int64
 50  maternas    1191 non-null     object
 51  lengua      1086743 non-null  int64
 52  cond_act    1086743 non-null  int64
 53  par_agre    1086743 non-null  int64
 54  ent_ocules  1086743 non-null  int64
 55  mun_ocules  1086743 non-null  int64
 56  loc_ocules  1086743 non-null  int64
 57  razon_m     1086743 non-null  int64
 58  dis_re_oax  1086743 non-null  int64
dtypes: int64(55), object(4)
memory usage: 489.2+ MB

Vemos el diccionario de datos:

In [36]:
dicc_mortalidad_2020 = pd.read_csv("/content/data/diccionario_de_datos/diccionario_datos_defunciones_registradas_2020.csv", encoding = "cp1252")
dicc_mortalidad_2020

,NOMBRE_CAMPO,LONGITUD,TIPO,NEMÓNICO,CATÁLOGO,RANGO_CLAVES
0,Entidad de registro,2,C,ent_regis,entidad_municipio_localidad_2020,01..32\t
1,Municipio o alcaldía de registro,3,C,mun_regis,entidad_municipio_localidad_2020,001..570 ...
2,Entidad de residencia habitual del (la) fallec...,2,C,ent_resid,entidad_municipio_localidad_2020,"01..35,99 ..."
3,Municipio o alcaldía de residencia habitual de...,3,C,mun_resid,entidad_municipio_localidad_2020,"001..570,999 ..."
4,Tamaño de localidad de residencia habitual del...,2,N,tloc_resid,tamaño_localidad,"01..17,99 ..."
5,Localidad de residencia habitual del (la) fall...,4,C,loc_resid,entidad_municipio_localidad_2020,"0001..6999,777,9999 ..."
6,Entidad de ocurrencia,2,C,ent_ocurr,entidad_municipio_localidad_2020,"01..35,99 ..."
7,Municipio o alcaldía de ocurrencia,3,C,mun_ocurr,entidad_municipio_localidad_2020,"001..570,999 ..."
8,Tamaño de localidad de ocurrencia,2,N,tloc_ocurr,tamaño_localidad,"01..17,99 ..."
9,Localidad de ocurrencia,4,C,loc_ocurr,entidad_municipio_localidad_2020,"0001..6999,777,9999 ..."
10,Causa de la defunción (lista detallada),4,C,causa_def,causa_defuncion,A000..Y899 ...
11,Causa de la defunción (lista mexicana),3,C,lista_mex,lista_mexicana,01..61
12,Sexo del (la) fallecido (a),1,N,sexo,sexo,"1,2,9 ..."
13,Edad del (la) fallecido (a),4,N,edad,edad,"1001..1023,1097,1098,2001..2029,2098,3001..301..."
14,Día de ocurrencia,2,N,dia_ocurr,dia,"1..31,99 ..."
15,Mes de ocurrencia,2,N,mes_ocurr,mes,"1..12,99 ..."
16,Año de ocurrencia,4,N,anio_ocur,año,"Año de estadística menos 1, Año de estadística"
17,Día de registro,2,N,dia_regis,dia,"1..31,99 ..."
18,Mes de registro,2,N,mes_regis,mes,"1..12,99\t"
19,Año de registro,4,N,anio_regis,año,Año estadística ...
20,Día de nacimiento del (la) fallecido (a),2,N,dia_nacim,dia,"1..31,99 ..."
21,Mes de nacimiento del (la) fallecido (a),2,N,mes_nacim,mes,"1..12,99 ..."
22,Año de nacimiento del (la) fallecido (a),4,N,anio_nacim,año,"Año de estadística menos 1, Año de estadística"
23,Ocupación del (la) fallecido (a),2,N,ocupacion,ocupacion,"1..11,97,98,99 ..."
24,Nivel de escolaridad del (la) fallecido (a) (e...,2,N,escolarida,escolaridad,"1..10,88,99 ..."
25,Estado conyugal (civil) del (la) fallecido (a),1,N,edo_civil,estado_civil,"1..6,8,9 ..."
26,Tipo de defunción (presunto),1,N,presunto,presunta_defuncion_violenta,"1..5,8 ..."
27,Ocurrió en el desempeño de su trabajo,1,N,ocurr_trab,ocurrio_trabajo,"1,2,8,9 ..."
28,Sitio de ocurrencia de la lesión,2,N,lugar_ocur,lugar_ocurrencia,"0..9,88 ..."
29,Condición de necropsia,1,N,necropsia,necropsia,"1,2,9 ..."
30,Condición de atención médica,1,N,asist_medi,asistencia_medica,"1,2,9 ..."
31,Sitio de ocurrencia de la defunción,2,N,sitio_ocur,sitio_ocurrencia,"1..12,99 ..."
32,Persona que certificó la defunción,1,N,cond_cert,certificante,"1..5,8,9 ..."
33,Nacionalidad del (la) fallecido (a),1,N,nacionalid,nacionalidad,"1,2,9 ..."
34,Afiliación a los servicios de salud (derechoha...,2,N,derechohab,derechohabiencia,"1..9,99 ..."
35,Condición de embarazo,1,N,embarazo,condicion_embarazo,"1..5,8,9 ..."
36,Causas relacionadas con el embarazo,1,N,rel_emba,relacion_con_embarazo,"1,2,8,9 ..."
37,Hora de la defunción,2,N,horas,hora,"0..23,99 ..."
38,Minuto de la defunción,2,N,minutos,minuto,"0..59,99 ..."
39,Causas detalladas CIE (capítulo),2,N,capitulo,capitulo_grupo,"1..18,20,22"
40,Causas detalladas CIE (grupo),2,N,grupo,capitulo_grupo,1..35
41,Lista de tabulación 1 para mortalidad de la CIE,3,C,lista1,lista1,"001..103,902, 903"
42,Lista mexicana de enfermedades (grupo),3,C,gr_lismex,grupo_lista_mexicana,"01..48,E49..E59"
43,Condición de violencia familiar,1,N,vio_fami,violencia_familiar,"1,2,8,9 ..."
44,Área urbana-rural de residencia habitual del (...,1,N,area_ur,area_urbana_rural,"1,2,9 ..."
45,Edad (agrupada) del (la) fallecido (a),2,C,edad_agru,edad_agrupada,01..30\t
46,Complicaron el embarazo,1,N,complicaro,complicaron_embarazo,"1,2,8,9 ..."
47,Día de certificación,2,N,dia_cert,dia,"1..31,99 ..."
48,Mes de certificación,2,N,mes_cert,mes,"1..12,99 ..."
49,Año de certificación,4,N,anio_cert,año,"Año de estadística menos 1, Año de estadística..."
50,Defunciones maternas totales,4,C,maternas,causa_defuncion,"A34X,F53,M830, causas que comienzan con O,B20...."
51,Condición de habla lengua indígena del (la) fa...,1,N,lengua,lengua_indigena,"1,2,8,9 ..."
52,Condición de actividad económica del (la) fall...,1,N,cond_act,condicion_actividad,"1,2,8,9 ..."
53,Parentesco del presunto agresor,2,N,par_agre,parentesco_agresor,"1..72,88,99 ..."
54,Entidad de ocurrencia de la lesión,2,C,ent_ocules,entidad_municipio_localidad_2020,"01..35,88,99 ..."
55,Municipio o alcaldía de ocurrencia de la lesión,3,C,mun_ocules,entidad_municipio_localidad_2020,"001..570,888,999 ..."
56,Localidad de ocurrencia de la lesión,4,C,loc_ocules,entidad_municipio_localidad_2020,"0001..6999,777,8888,9999 ..."
57,Defunciones para calcular la razón de la morta...,1,N,razon_m,razon_materna,1\t
58,Distritos de registro de Oaxaca,3,N,dis_re_oax,entidad_municipio_localidad_2020,"901..930,999"

### Morbilidad
Veamos la segunda base de datos.

In [39]:
df_morbilidad_2020 = pd.read_csv("/content/data/conjunto_de_datos_esep_morbilid_2020/conjunto_de_datos/conjunto_de_datos_esep_morbilid_2020.csv")

df_morbilidad_2020.head(10)

,SMOANIO,SMOENTIDAD,SMOMUNIC,SMOCONSEC,SMOTAMLOC,SMOTIPOEST,SMOAGEB,SMOCLAVE,SMOTOTAL,SMOHOMB,SMOMUJE,SMODIAS,SMODEFUN
0,2020,1,1,1,1,21,888,59,6,4,2,11,0
1,2020,1,1,1,1,21,888,64,1,1,0,2,0
2,2020,1,1,1,1,21,888,83,2,2,0,2,0
3,2020,1,1,1,1,21,888,92,1,0,1,1,0
4,2020,1,1,1,1,21,888,116,2,1,1,6,0
5,2020,1,1,1,1,21,888,117,465,31,434,526,0
6,2020,1,1,1,1,21,888,118,2,2,0,2,0
7,2020,1,1,1,1,21,888,120,3,1,2,3,0
8,2020,1,1,1,1,21,888,121,3,2,1,9,0
9,2020,1,1,1,1,21,888,122,2,1,1,7,0

In [40]:
df_morbilidad_2020.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159259 entries, 0 to 159258
Data columns (total 13 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   SMOANIO     159259 non-null  int64
 1   SMOENTIDAD  159259 non-null  int64
 2   SMOMUNIC    159259 non-null  int64
 3   SMOCONSEC   159259 non-null  int64
 4   SMOTAMLOC   159259 non-null  int64
 5   SMOTIPOEST  159259 non-null  int64
 6   SMOAGEB     159259 non-null  object
 7   SMOCLAVE    159259 non-null  int64
 8   SMOTOTAL    159259 non-null  int64
 9   SMOHOMB     159259 non-null  int64
 10  SMOMUJE     159259 non-null  int64
 11  SMODIAS     159259 non-null  int64
 12  SMODEFUN    159259 non-null  int64
dtypes: int64(12), object(1)
memory usage: 15.8+ MB

Veamos el diccionario de datos para entender la base de datos.

In [42]:
dicc_morbilidad_2020 = pd.read_csv("/content/data/conjunto_de_datos_esep_morbilid_2020/diccionario_de_datos/diccionario_de_datos_esep_morbilid_2020.csv", encoding = "cp1252")
dicc_morbilidad_2020

,NOMBRE_CAMPO,LONGITUD,TIPO,NEMÓNICO,CATÁLOGO,RANGO_CLAVESALIDO
0,Año 2020,4,Int,SMOANIO,tc_espe_año,NaN
1,Entidad,2,Varchar,SMOENTIDAD,tc_esep_entidad_mun,01..32
2,Municipio o alcaldía,3,Varchar,SMOMUNIC,tc_esep_entidad_mun,"001..570,600"
3,Consecutivo,4,Int,SMOCONSEC,tc_esep_consecutivo,01..300
4,Tamaño de la localidad en donde se asienta la ...,2,Int,SMOTAMLOC,tc_esep_tamaño_localidad,1..18
5,Tipo de establecimiento,2,Int,SMOTIPOEST,tc_esep_tipo_establecimiento,21..26
6,AGEB,4,Varchar,SMOAGEB,tc_esep_ageb,10..525A
7,Clave de morbilidad,6,Int,SMOCLAVE,tc_esep_clave_morbilid,0..999999
8,Total,6,Int,SMOTOTAL,tc_esep_egresos,0..999999
9,Hombres,6,Int,SMOHOMB,tc_esep_egresos,0..999999
10,Mujeres,6,Int,SMOMUJE,tc_esep_egresos,0..999999
11,Días estancia,6,Int,SMODIAS,tc_esep_días estancia,0..999999
12,Defunciones,6,Int,SMODEFUN,tc_esep_defunciones,0..999999

Me interesa estudiar cuáles fueron los principales padecimientos, o morbilidad registrada, pero esta se encuentra en clave, por lo que revisaré las claves utilizadas.

In [46]:
claves_morbilidad_2020 = pd.read_csv("/content/data/conjunto_de_datos_esep_morbilid_2020/catalogos/tc_esep_clave_morbilid.csv", encoding = "cp1252")
claves_morbilidad_2020

    CLAVE_CIE10\tSMOCLAV                                         NOMBRE_CMO
0                001\t60                                           \tCólera
1                002\t61                  \tFiebres tifoidea y paratifoidea
2                003\t62                                       \tShigelosis
3                004\t63                                        \tAmebiasis
4                005\t64  \tDiarrea y gastroenteritis de presunto origen...
..                   ...                                                ...
294             296\t373                   \tAtención y examen de postparto
295             297\t374  \tPersonas en contacto con los servicios de sa...
296             298\t375  \tPersonas en contacto con los servicicios de ...
297               299378                  U071 –COVID-19 CASOS CONFIRMADOS
298               300379       U072 – COVID-19 CASOS PROBABLES/ SOSPECHOSOS

[299 rows x 2 columns]

## 2. Estructura de los datos que se descargaron sobre personas desaparecidas a nivel nacional